name: Deploy Infraestructura — CloudFormation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-infra:
    name: Desplegar VPC y S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Dar permisos al script
        run: chmod +x Scripts/deploy-infra.sh

      - name: Desplegar infraestructura
        run: ./Scripts/deploy-infra.sh
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
